# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first

Content.create(language: "Bhojpuri",title: "Rakhtanchal",release_date: "2020",genre: "crime,action,drama",banner: "https://qqcdnpictest.mxplay.com/pic/ca7a124443044bf3c1f8ea52c8b7f9fc/en/2x3/320x480/test_pic1689833329737.webp",category: "web-series",trailer_link: "https://www.youtube.com/watch?v=ISORfez27og", vip_status: 1, is_slider: 0)
Content.create(language: "Bhojpuri",title: "Bhaukaal",release_date: "2020",genre: "crime,action,drama",banner: "https://qqcdnpictest.mxplay.com/pic/775ad3b682fde6a608559a60986b230d/en/2x3/320x480/test_pic1698305827480.webp",category: "web-series",trailer_link: "https://www.youtube.com/watch?v=ISORfez27og", vip_status: 1, is_slider: 0)
Content.create(language: "Bhojpuri",title: "Apaharan",release_date: "2023",genre: "crime,comedy,drama",banner: "https://v3img.voot.com/resizeMedium,w_810,h_1080/v3Storage/assets/3x4-new-1700146318041.jpg",category: "web-series",trailer_link: "https://www.youtube.com/watch?v=ISORfez27og", vip_status: 1, is_slider: 0)
Content.create(language: "Rajasthani",title: "Asur",release_date: "2023",genre: "crime,thriller,drama",banner: "https://v3img.voot.com/resizeMedium,w_810,h_1080/v3Storage/assets/3x4-1700054711204.jpg",category: "web-series",trailer_link: "https://www.youtube.com/watch?v=ISORfez27og", vip_status: 1, is_slider: 0)
Content.create(language: "English",title: "Bandon Mein Tha Dum",release_date: "2021",genre: "documentary,sports",banner: "https://v3img.voot.com/resizeMedium,w_810,h_1080/v3Storage/assets/bandonmeinthadum_verical-1699964591247.jpeg",category: "web-series",trailer_link: "https://www.youtube.com/watch?v=ISORfez27og", vip_status: 1, is_slider: 1)
Content.create(language: "Hindi",title: "Kaalkoot",release_date: "2023",genre: "crime,action,thriller,drama",banner: "https://v3img.voot.com/resizeMedium,w_810,h_1080/v3Storage/assets/3x4-1700055940311.jpg",category: "web-series",trailer_link: "https://www.youtube.com/watch?v=ISORfez27og", vip_status: 1, is_slider: 0)
Content.create(language: "Marathi",title: "Taali",release_date: "2023",genre: "crime,drama,thriller",banner: "https://v3img.voot.com/resizeMedium,w_810,h_1080/v3Storage/assets/3x4-1700048934372.jpg",category: "web-series",trailer_link: "https://www.youtube.com/watch?v=ISORfez27og", vip_status: 1, is_slider: 0)
Content.create(language: "Hindi",title: "Ishq Next Door",release_date: "2023",genre: "drama,romance",banner: "https://v3img.voot.com/resizeMedium,w_810,h_1080/v3Storage/assets/ind_3x4-1692799134037.jpg",category: "web-series",trailer_link: "https://www.youtube.com/watch?v=ISORfez27og", vip_status: 1, is_slider: 0)
Content.create(language: "English",title: "Loki",release_date: "2023",genre: "drama,comics,action,thriller",banner: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_3840/sources/r1/cms/prod/7030/1607030-v-924e1d5a7914",category: "web-series",trailer_link: "https://www.youtube.com/watch?v=ISORfez27og", vip_status: 1, is_slider: 0)
Content.create(language: "Hindi",title: "Aakhri Sach",release_date: "2023",genre: "drama,crime,thriller,documentary",banner: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_3840/sources/r1/cms/prod/7505/1597505-v-a138fb6088a5",category: "web-series",trailer_link: "https://www.youtube.com/watch?v=ISORfez27og", vip_status: 1, is_slider: 0)
Content.create(language: "Telagu",title: "Rudra",release_date: "2023",genre: "drama,romance,thriller",banner: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_3840/sources/r1/cms/prod/7460/1617460-v-cfbd9adb4eff",category: "web-series",trailer_link: "https://www.youtube.com/watch?v=ISORfez27og", vip_status: 1, is_slider: 0)
Content.create(language: "Marathi",title: "Taaza Khabar",release_date: "2023",genre: "drama,fantasy,thriller,crime",banner: "https://img10.hotstar.com/image/upload/f_auto,q_90,w_3840/sources/r1/cms/prod/2547/1612547-v-af15743b15eb",category: "web-series",trailer_link: "https://www.youtube.com/watch?v=ISORfez27og", vip_status: 1, is_slider: 0)

# Episode.create(content_id: 1, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://qqcdnpictest.mxplay.com/pic/cabbda9ca9131dfc76011992c351fcb7/en/16x9/320x180/7bba6845608c0d8781d353ee9f762541_1920x1080.webp", title: "The Bad Blood", runtime: "26 min", cast: "Kranti Prakash Jha, Nikitin Dheer, Chitranjan Tripathy, Basu Soni, Vikram Kochchar, Shashi Chaturvedi, Daya Shankar Pandey, Ravi Khanvilkar, Soundarya Sharma, Pravina Deshpandey, Gyan Prakash, Ronjini Chakroborthy, Krishna Bisht", director: "Ritam Srivastav",story: "Waseem Khan is the most terrifying name in the city of Varanasi unless Vijay Singh appears. However, how did once an innocent, family man become the most dreaded don? When things take a violent turn at Vijay Singh’s sister’s wedding, all is lost for him. With nothing more to lose, all Vijay Singh needs to get is cold revenge")

# Episode.create(content_id: 1, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://qqcdnpictest.mxplay.com/pic/e807b21f3080dabb2e01700ce50cf4d9/en/16x9/320x180/e20888e68878bfc881aae380cf141574_1920x1080.webp", title: "High Stakes", runtime: "26 min", cast: "Kranti Prakash Jha, Nikitin Dheer, Chitranjan Tripathy, Basu Soni, Vikram Kochchar, Shashi Chaturvedi, Daya Shankar Pandey, Ravi Khanvilkar, Soundarya Sharma, Pravina Deshpandey, Gyan Prakash, Ronjini Chakroborthy, Krishna Bisht", director: "Ritam Srivastav",story: "With political battles of elections comes the underworld battles of goons backed by the politicians. A vengeful Vijay Singh is out for making things even with Waseem Khan. While Waseem Khan is backed by the ruling party of Pujari Singh, Vijay Singh has opposition and power-thirsty, Sahib Singh, on his side. As admiration and political systems get involved, things get really violent, really soon. Who is to lose this time? Will the electorate battle take an ugly turn?")

# Episode.create(content_id: 1, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://qqcdnpictest.mxplay.com/pic/e0935c6508e06a7972cee3fb1ddcd40e/en/16x9/320x180/f1ab895f0cd3b54dc5966b95854836e8_1920x1080.webp", title: "You Win, You Die!", runtime: "27 min", cast: "Kranti Prakash Jha, Nikitin Dheer, Chitranjan Tripathy, Basu Soni, Vikram Kochchar, Shashi Chaturvedi, Daya Shankar Pandey, Ravi Khanvilkar, Soundarya Sharma, Pravina Deshpandey, Gyan Prakash, Ronjini Chakroborthy, Krishna Bisht", director: "Ritam Srivastav",story: "Communal riots, booth capturing and every other outlaw activity is covered in the see-saw election. Pujari Singh faces a defeat but as Vijay Singh exits Ghazipur, things might not remain the same")

# Episode.create(content_id: 1, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://qqcdnpictest.mxplay.com/pic/6593ef07716e01cc8507b38e6f1a6c4f/en/16x9/320x180/c9ed38d7793852b4857b71b89b898c6a_1920x1080.webp", title: "Black Gold", runtime: "25 min", cast: "Kranti Prakash Jha, Nikitin Dheer, Chitranjan Tripathy, Basu Soni, Vikram Kochchar, Shashi Chaturvedi, Daya Shankar Pandey, Ravi Khanvilkar, Soundarya Sharma, Pravina Deshpandey, Gyan Prakash, Ronjini Chakroborthy, Krishna Bisht", director: "Ritam Srivastav",story: "A don is said to be as strong as his gang members supporting him. Seeing the right time, Vijay Singh takes down a crucial member of the Waseem Khan gang who also happens to be his right hand. Vijay Singh now moves close to the movies of his revenge. However, Waseem Khan will have to be on his foot now as Vijay Singh inches closer to him. After the elimination of his best man, he hires Sanki Pandey, a manic man who is his hope to save the business.")

# Episode.create(content_id: 1, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://qqcdnpictest.mxplay.com/pic/3a869f6836ba1eed9059c04242440b3f/en/16x9/320x180/7790efc4da2cf966e9fa624cbc1ce902_1920x1080.webp", title: "The Blood Feud", runtime: "23 min", cast: "Kranti Prakash Jha, Nikitin Dheer, Chitranjan Tripathy, Basu Soni, Vikram Kochchar, Shashi Chaturvedi, Daya Shankar Pandey, Ravi Khanvilkar, Soundarya Sharma, Pravina Deshpandey, Gyan Prakash, Ronjini Chakroborthy, Krishna Bisht", director: "Ritam Srivastav",story: "The latest member of Waseem Khan’s gang, Sanky Pandey is behind Vijay Singh and will not rest till he is successful in his motives. Vijay finds himself in the centre of an attack at the boot camp. To his surprise, an unlikely couple comes to his rescue. Love blossoms as the couple save his life. Who are these people? Does the couple know Vijay Singh?")

# Episode.create(content_id: 1, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://qqcdnpictest.mxplay.com/pic/5df6f10e7b8cf4ebb486eaa2bc3c142e/en/16x9/320x180/cc0ec1cb1a15f184e6b981c3857e5d6b_1920x1080.webp", title: "Cat and Mouse", runtime: "25 min", cast: "Kranti Prakash Jha, Nikitin Dheer, Chitranjan Tripathy, Basu Soni, Vikram Kochchar, Shashi Chaturvedi, Daya Shankar Pandey, Ravi Khanvilkar, Soundarya Sharma, Pravina Deshpandey, Gyan Prakash, Ronjini Chakroborthy, Krishna Bisht", director: "Ritam Srivastav",story: "If there is one thing Sanki Pandey cannot resist, it is his lusty desires. Vijay Singh knows this weakness and sets a honey trap for Sanki Pandey. However, as he lets his guards loose, the alcohol sold by Vijay Singh leads to the death of several people in the city. Is this a trap? Will Vijay Singh now come in the public radar?")

# Episode.create(content_id: 1, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://qqcdnpictest.mxplay.com/pic/6dabc05c81facd5e9df87242b5fce6b9/en/16x9/320x180/f59f1c994d4e04eabf34d27181b6d536_1920x1080.webp", title: "Try Till You Succeed", runtime: "21 min", cast: "Kranti Prakash Jha, Nikitin Dheer, Chitranjan Tripathy, Basu Soni, Vikram Kochchar, Shashi Chaturvedi, Daya Shankar Pandey, Ravi Khanvilkar, Soundarya Sharma, Pravina Deshpandey, Gyan Prakash, Ronjini Chakroborthy, Krishna Bisht", director: "Ritam Srivastav",story: "The attacks on Vijay Singh do not seem to stop. Vijay Singh and his gang are on the radar. He then decides to eliminate the route of all evil. A distressed Vijay Singh is now on the lookout to kill Pujari Singh at a public gathering. Will this be the end of Waseem’s story? Will Vijay Singh be able to get away easily? Watch the high-drama episode as the story takes a climactic turn.")

# Episode.create(content_id: 1, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://qqcdnpictest.mxplay.com/pic/58aa659c01403548095f62d4d2340001/en/16x9/320x180/ee9714f60ee830d0f244dac2f99d0053_1920x1080.webp", title: "Land Is Your Mother", runtime: "24 min", cast: "Kranti Prakash Jha, Nikitin Dheer, Chitranjan Tripathy, Basu Soni, Vikram Kochchar, Shashi Chaturvedi, Daya Shankar Pandey, Ravi Khanvilkar, Soundarya Sharma, Pravina Deshpandey, Gyan Prakash, Ronjini Chakroborthy, Krishna Bisht", director: "Ritam Srivastav",story: "An influential and powerful politician, Baba, arrives in the story. He makes an exotic offer to Vijay Singh as well as Waseem Khan. The offer is such that they both cannot refuse. On the other hand, Seems is exposed and Vijay Singh’s cover is revealed as she tries to plan Sanki Pandey’s murder")

# Episode.create(content_id: 1, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://qqcdnpictest.mxplay.com/pic/c2d97b49d1764c98964dffacb2fc9587/en/16x9/320x180/48195c9d04e34cd0bcd9ecf341029e47_1920x1080.webp", title: "Public Enemy", runtime: "25 min", cast: "Kranti Prakash Jha, Nikitin Dheer, Chitranjan Tripathy, Basu Soni, Vikram Kochchar, Shashi Chaturvedi, Daya Shankar Pandey, Ravi Khanvilkar, Soundarya Sharma, Pravina Deshpandey, Gyan Prakash, Ronjini Chakroborthy, Krishna Bisht", director: "Ritam Srivastav",story: " Waseem Khan’s plans come into force and Vijay Singh becomes the villain in the public eye. Seema meets with Sanki Pandey and their meeting ends brutally as Vijay Singh gets attacked and falls in the river. Will this be the end of Vijay Singh’s life? Will he be able to take his revenge?")


# Episode.create(content_id: 3, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://v3img.voot.com/resizeMedium,w_960,h_360/kimg/kimg/fd1b5a8a16fc4770813f6c8c65311bea_1280X720.jpg", title: "Meet the kidnapping expert", runtime: "25 min", cast: "Arunoday Singh, Mahie Gill, Varun Badola, Sanjay Batra, Monica Chaudhary, Nidhi Singh, Saanand Verma, Neha Kaul, Sidharth Sengupta, Edgestorm Ventures LLP, Sidharth Sengupta-Jyoti Sagar", director: "Sidharth Sengupta",story: "Senior Inspector Rudra Srivastava, once known as the kidnapping expert, is jobless and a convict after his involvement in a high-profile kidnapping case. One day at a local bar, a beautiful lady offers him a proposal.")
# Episode.create(content_id: 3, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://v3img.voot.com/resizeMedium,w_960,h_360/kimg/kimg/5d220269d86c4558ba9ef2023bf4894f_1280X720.jpg", title: "Is it worth the risk?", runtime: "24 min", cast: "Arunoday Singh, Mahie Gill, Varun Badola, Sanjay Batra, Monica Chaudhary, Nidhi Singh, Saanand Verma, Neha Kaul, Sidharth Sengupta, Edgestorm Ventures LLP, Sidharth Sengupta-Jyoti Sagar", director: "Sidharth Sengupta",story: "As Madhu Tyagi briefs Rudra Shrivastav about Anusha, Rudra decides to meet her before kidnapping her. Escaping from the eyes of Anusha's bodyguards, Rudra sneaks into her college")
# Episode.create(content_id: 3, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://v3img.voot.com/resizeMedium,w_960,h_360/kimg/kimg/596a9468e57743f2984c56ebb6754e09_1280X720.jpg", title: "Take the girl and run!", runtime: "24 min", cast: "Arunoday Singh, Mahie Gill, Varun Badola, Sanjay Batra, Monica Chaudhary, Nidhi Singh, Saanand Verma, Neha Kaul, Sidharth Sengupta, Edgestorm Ventures LLP, Sidharth Sengupta-Jyoti Sagar", director: "Sidharth Sengupta",story: "Rudra reaches Anusha's best friend's wedding venue, and realises that Anusha is closely guarded. Rudra has very little time to kidnap Anusha before her father arrives")
# Episode.create(content_id: 3, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://v3img.voot.com/resizeMedium,w_960,h_360/kimg/kimg/9b59890224fe432abd6b4006491b38c0_1280X720.jpg", title: "The call for ransom", runtime: "23 min", cast: "Arunoday Singh, Mahie Gill, Varun Badola, Sanjay Batra, Monica Chaudhary, Nidhi Singh, Saanand Verma, Neha Kaul, Sidharth Sengupta, Edgestorm Ventures LLP, Sidharth Sengupta-Jyoti Sagar", director: "Sidharth Sengupta",story: "After reaching Rishikesh, Rudra and Anusha make the ransom call to Govind Tyagi. Govind's security lead, Saxena, launches an independent search for Anusha.")
# Episode.create(content_id: 3, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://v3img.voot.com/resizeMedium,w_960,h_360/kimg/kimg/511cb0d331af4eeea758f2a7937f2ba7_1280X720.jpg", title: "The calm before the storm", runtime: "26 min", cast: "Arunoday Singh, Mahie Gill, Varun Badola, Sanjay Batra, Monica Chaudhary, Nidhi Singh, Saanand Verma, Neha Kaul, Sidharth Sengupta, Edgestorm Ventures LLP, Sidharth Sengupta-Jyoti Sagar", director: "Sidharth Sengupta",story: "Tyagi arranges the ransom money and travels alone to deliver it. Despite the warnings, he is followed by Saxena. Will Saxena's actions cause problems for Rudra?")
# Episode.create(content_id: 3, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://v3img.voot.com/resizeMedium,w_960,h_360/kimg/kimg/fd94fc3336ed4bdd9b5bc4115f76fe71_1280X720.jpg", title: "Home with a dead girl", runtime: "25 min", cast: "Arunoday Singh, Mahie Gill, Varun Badola, Sanjay Batra, Monica Chaudhary, Nidhi Singh, Saanand Verma, Neha Kaul, Sidharth Sengupta, Edgestorm Ventures LLP, Sidharth Sengupta-Jyoti Sagar", director: "Sidharth Sengupta",story: "When Rudra discovers that Anusha is dead, he stuffs her body into a bag and travels with it. When he gets home, he finds the cops waiting for him. Will Rudra be apprehended?")
# Episode.create(content_id: 3, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://v3img.voot.com/resizeMedium,w_960,h_360/kimg/kimg/679e8917916146a6bfff276feaaa06c4_1280X720.jpg", title: "Caught in your own web", runtime: "24 min", cast: "Arunoday Singh, Mahie Gill, Varun Badola, Sanjay Batra, Monica Chaudhary, Nidhi Singh, Saanand Verma, Neha Kaul, Sidharth Sengupta, Edgestorm Ventures LLP, Sidharth Sengupta-Jyoti Sagar", director: "Sidharth Sengupta",story: "Rudra is greeted warmly at the police station. In addition, he is appointed as the primary investigator in the Anusha's kidnapping case.")
# Episode.create(content_id: 3, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://v3img.voot.com/resizeMedium,w_960,h_360/kimg/kimg/f643e90bed704131a2b5ede5fc96256c_1280X720.jpg", title: "A matter of 10 crores", runtime: "23 min", cast: "Arunoday Singh, Mahie Gill, Varun Badola, Sanjay Batra, Monica Chaudhary, Nidhi Singh, Saanand Verma, Neha Kaul, Sidharth Sengupta, Edgestorm Ventures LLP, Sidharth Sengupta-Jyoti Sagar", director: "Sidharth Sengupta",story: "Rudra successfully disposes of Anusha's body. Further, Tyagi sets a reward of Rs 10 Cr for information on the murder. What effect will it have on Rudra? ")
# Episode.create(content_id: 3, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://v3img.voot.com/resizeMedium,w_960,h_360/kimg/kimg/8ab751d8fdbb4c33867914ffbe22ba1a_1280X720.jpg", title: "The check and the mate", runtime: "21 min", cast: "Arunoday Singh, Mahie Gill, Varun Badola, Sanjay Batra, Monica Chaudhary, Nidhi Singh, Saanand Verma, Neha Kaul, Sidharth Sengupta, Edgestorm Ventures LLP, Sidharth Sengupta-Jyoti Sagar", director: "Sidharth Sengupta",story: "Saxena suspects that Rudra is involved in Anusha's kidnapping and promises to provide evidence. Meanwhile, Rudra learns about Anusha's closest person.")
# Episode.create(content_id: 3, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://v3img.voot.com/resizeMedium,w_960,h_360/kimg/kimg/f4ea44c4c6ce49ad8f80cbdbc86872e7_1280X720.jpg", title: "The most wanted criminal", runtime: "22 min", cast: "Arunoday Singh, Mahie Gill, Varun Badola, Sanjay Batra, Monica Chaudhary, Nidhi Singh, Saanand Verma, Neha Kaul, Sidharth Sengupta, Edgestorm Ventures LLP, Sidharth Sengupta-Jyoti Sagar", director: "Sidharth Sengupta",story: "Rudra escapes from the police station and is chased by cops and Saxena's men. Later, to save Ranjana, Rudra calls Govind for help.")
# Episode.create(content_id: 3, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://v3img.voot.com/resizeMedium,w_960,h_360/kimg/kimg/275ebae999ac472f83689b4d8c98cd88_1280X720.jpg", title: "When the reality strikes", runtime: "19 min", cast: "Arunoday Singh, Mahie Gill, Varun Badola, Sanjay Batra, Monica Chaudhary, Nidhi Singh, Saanand Verma, Neha Kaul, Sidharth Sengupta, Edgestorm Ventures LLP, Sidharth Sengupta-Jyoti Sagar", director: "Sidharth Sengupta",story: "Rudra learns that a stranger, who rescued him is also a part of the game. Later, Rudra warns Saxena of consequences if he tries to harm Ranjana.")
# Episode.create(content_id: 3, season: 1, url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",thumbnail: "https://v3img.voot.com/resizeMedium,w_960,h_360/kimg/kimg/c696ac2a49c646b0979388c235a77762_1280X720.jpg", title: "The final showdown", runtime: "26 min", cast: "Arunoday Singh, Mahie Gill, Varun Badola, Sanjay Batra, Monica Chaudhary, Nidhi Singh, Saanand Verma, Neha Kaul, Sidharth Sengupta, Edgestorm Ventures LLP, Sidharth Sengupta-Jyoti Sagar", director: "Sidharth Sengupta",story: "As a thrilling game of cat and mouse begins, Tyagi orders Saxena to kill both Rudra and Ranjana. Finally, Rudra and Malini come face to face.")



# Subscription.create(name: "Starter", duration: "3 months", real_amount: "200", offer_amount: "500")
# Subscription.create(name: "Premium", duration: "6 months", real_amount: "300", offer_amount: "500")
# Subscription.create(name: "Vip", duration: "12 months", real_amount: "500", offer_amount: "500")


# Coupon.create(code: "FLAT10",offer: "Get Flat 10% of on all subscriptions",status: 1)
# Coupon.create(code: "THANKS20",offer: "Get Flat 20% of on all subscriptions",status: 1)
# Coupon.create(code: "CHRISTMAS30",offer: "Get Flat 30% of on all subscriptions",status: 1)
# Coupon.create(code: "HAPPYNEWYEAR40",offer: "Get Flat 40% of on all subscriptions",status: 1)
